language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
script: ./gradlew build jacocoTestReport coveralls
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key: GITHUB_OAUTH_TOKEN
  file_glob: true
  file: target/*.jar
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - COVERALLS_REPO_TOKEN=HXEwzJTSlU7LuNDIjn4ERLeYSkoXbEFPi
  - secure: pYqrXGzKS8YIrBEYu06mkei4rumUCl7maaj65ta9vglXaiyfIP51m8+CaogTX0J4jBuajAQmMstDvoxrhhaCDwPmUpM/BLT9NQtl3lnryyj7HK4zn3yWHzw4fQ0+fYWGoCxeQ/7/WRqJTj5e6k4e/NZ3qJidrdfp2/x9xMQKWWd5AQN5BzPhI+ZhSyE8fTaa9uVitUn8Xe9nc9+x0agPQirNXR5OQ9aY0xwavbD09zSaQLHCDqck2LP73BRdmhNZe27Vhuht0Xpl5L7XhyIF6Jc2JBiecZxkclj/qYQkouQJ0e3itMmnmyU9+nqP92kZ0QiLSZx3lnbCw4B85EJ80zvlHHtLXmt5eIr6VfT07X/YTW1bTfvsxNaxg2nPX3ZSL+3BJyB9vitcRcIjvXOF6dYK2XPaY+8OipvzJ7f+bFvFD0yGl0hOnjtDx1dMvP8TP1WHtSXd/pQC6uvXcIQhSN7/f9o2EzT7/VrBnA96ei5OFhDmH5awipUikbUg1Uu5Rqb0KLG0UBXomVlqlqhTa4bpnlLy5s6S7d0HB4LgqTIVBwMYK9Fdqtnw+mLdjR3KyjuZy8o3Qs9Hb3fHcsI79ARtuFs2YbkuaA0Rps4wvvMDwwcYlDN/cDO328qokGngDRXtT7UtiAkjjmcVGf2KgQNe9WsJ4GzEyl5LD+nbVvA=
